### ISSUE TITLE
Suggestion: Add Resource.patch(data) method

### ISSUE THREAD

**Issue by nlenoire** [evert/ketting#83]
Hi,

I'm currently not yet using your library, but it looks promising.
However, it would be nice if you could add native support to the PATCH http method. Is it something you could consider?

Regards,
-NL

**Comment by evert** [comment]
It's an interesting idea. I don't know yet exactly that the appropriate way is. There is a `fetch` method for 'everything else' and `PATCH` itself doesn't have clear semantics in terms of REST.

How would this API look like if it were up to you?

**Comment by nlenoire** [comment]
A simple API like Resource.patch(body) would be fine enough, I guess. It would be very similar to Resource.put(body), but with the "update" semantic rather than with the "create or replace" semantic of PUT.

**Comment by evert** [comment]
One of the potential issues with doing that, is that typically a `PATCH` _should_ probably have a different `Content-Type` than `PUT` or `GET`, because it's effectively a different format.

The only case where this is probably not true, is cases where you just use `application/json` for everything, but this is arguably an anti-pattern.

So the ideal solution to me is one that at least satisfies that condition. What content-types do you use for `PATCH` vs `GET`/`PUT` ?

**Comment by nlenoire** [comment]
Personally, I don't rely too much on explicit media-types for my requests as you suggest (i.e. I use `application/json`). But that's mainly because the APIs I worked on are primarily internal APIs. Otherwise, I could have specified my own media-type extending `application/json`, but I don't see this as a strong requirement. Btw, what is the media-type you use for `PUT` and `POST`, then?

Anyhow, if you want a more suitable and standardized way, a `PATCH` request could be triggered with `application/json-patch+json` media-type (see [RFC6902](https://tools.ietf.org/html/rfc6902), but it could also be considered as killing a fly with a hammer in many circumstances.

**Comment by evert** [comment]
For sending resources to the server (and receiving them), we use a media-type in the format:

    application/vnd.[vendorname].hal+json

We're not using `PATCH` yet. We actually started with `PUT` with the assumption that we would want `PATCH` down the road, but there was never a valid case for not replacing the whole resource.

I'd imagine once we need `PATCH` we would do so by writing a middleware that basically does:

* Doing an equivalent of an internal GET request.
* Patching the body.
* Doing the equivalent of an internal PUT request.

Our validation is tied to media-types, so for this case we would likely want to use a new mediatype, or use an existing one like `application/json-patch+json`.

Maybe it's still worth adding just a simple `PATCH` request per your exact suggestion. We can always change this if it turns out that it doesn't work well for the common case.
